/** YouTube catalogs scraped from the live site. Titles are the publisher's own. */
export type Video = { id: string; title: string };

export const YT_THUMB = (id: string) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
export const YT_EMBED = (id: string) => `https://www.youtube.com/embed/${id}`;
export const YT_WATCH = (id: string) => `https://www.youtube.com/watch?v=${id}`;

export const TINNITUS_SERIES: Video[] = [
  { id: "poyYwxuNyEE", title: "Welcome to Tinnitus Relief Management" },
  { id: "UUV27rRiQTQ", title: "Types of Tinnitus" },
  { id: "LtFO0jpASOI", title: "Tinnitus - You're Not Alone" },
  { id: "VIFUapyvoIU", title: "Effects of Tinnitus" },
  { id: "DBm9xRy7IbA", title: "Causes of Tinnitus" },
  { id: "9szfpgV8W5Q", title: "Sound Therapy for Tinnitus" },
  { id: "pxKWWN3H4A0", title: "Types of Tinnitus Therapy" },
  { id: "Yxh_0QE8bec", title: "Sound Therapy for Tinnitus" },
  { id: "Qb0elaE6ORI", title: "Tinnitus and What To Do When It's Quiet" },
  { id: "qE3kJiHVneI", title: "Tinnitus at Night" },
  { id: "l21zSto4BtU", title: "Apps for Tinnitus" },
  { id: "74ju8CoFDwg", title: "Sound Searching and Tinnitus" },
  { id: "lB2eJQ6m0bI", title: "Mental Health and Tinnitus" },
  { id: "TXFhiBsMVpw", title: "Tinnitus and Mental Health When to Seek Help" },
  { id: "b1UXXtQ9qQ8", title: "Self Care and Tinnitus" },
  { id: "P99mFcdrstg", title: "Tinnitus Tips for Bad Days" },
  { id: "5fffjJ-qzfs", title: "Tinnitus - Prescriptions and Supplements" },
  { id: "ApvTihSNy4Q", title: "Anxiety Reduction for Tinnitus" },
  { id: "ek1QOmHY7lk", title: "Hearing Loss and Tinnitus" },
  { id: "gutxUJTDf1Q", title: "Hearing Aids and Tinnitus" },
  { id: "p7HlSp7Aq2k", title: "Tinnitus - Hearing Aids are not One Size Fits All" },
  { id: "kvkq5O403KY", title: "Tinnitus - Finding the Right Audiologist" },
  { id: "tz9bZ80Zo8Q", title: "How to Find the Right Audiologist When You Have Tinnitus" },
  { id: "IWf-Ddebk8s", title: "Healthy Choices and Tinnitus" },
  { id: "zRDbk3X1Qmo", title: "Heart Health and Tinnitus" },
  { id: "T0ZGZzOS568", title: "Walking and Tinnitus" },
  { id: "CZp2peR1y98", title: "Heart Healthy Meals and Tinnitus" },
  { id: "pq7EAUyMf-I", title: "Yoga and Tinnitus" },
  { id: "qTzvhaMkNGY", title: "Tinnitus and Advocating for Yourself" },
  { id: "bp7oeVoMGb8", title: "Tinnitus and Food Mindfulness" },
  { id: "BM6HZvggzrM", title: "Sleep and Tinnitus" },
  { id: "Bx46TTj2I5A", title: "A Good Night's Sleep and Tinnitus" },
  { id: "e-b8RAMbQMI", title: "Tinnitus and Tracking Sleep" },
  { id: "Ou7rwavCtlo", title: "Tinnitus and Sleep Habits" },
  { id: "HDoU1iqJYQo", title: "Sleep Aids and Tinnitus" },
  { id: "XwHo9D8lNmM", title: "Tinnitus - When to See A Doctor About Sleep" },
  { id: "PLc1eIsuHu8", title: "Professionals on Your Tinnitus Team" },
  { id: "Hfcxuft-bEg", title: "Tinnitus and Your Primary Care Provider" },
  { id: "-rZYQVIIt3c", title: "Your Tinnitus Team" },
  { id: "Mzd6GXeFW9I", title: "Tinnitus and Neck Injuries4" },
  { id: "lBx4oGMi6-0", title: "Tinnitus and Mental & Spiritual Health" },
  { id: "HPwef59JK2A", title: "Tinnitus and Other Professionals" },
  { id: "4tXZs-O1Mio", title: "Tinnitus and Your Neurologist" },
  { id: "nxOM3dJbITU", title: "What if Your Tinnitus Changes" },
  { id: "tGoWeBV2g7Y", title: "Lifelong Tinnitus Tips" },
  { id: "d03ADewpdyA", title: "Medications Can Affect Tinnitus" },
  { id: "6dBU74n9hc4", title: "Tinnitus - It Gets Better" },
  { id: "SIcox7lvP4M", title: "Tinnitus - Talk With Your Doctor" },
  { id: "SWgUG6zLXqY", title: "Tinnitus Research Continues" },
  { id: "Joejd70yy7U", title: "Tinnitus - A Few Final Words" },
];

export const VIDEO_SECTIONS: { name: string; videos: Video[] }[] = [
  {
    name: "PATIENT PORTAL VIDEOS",
    videos: [
      { id: "4eG7Vg7K4yo", title: "Patient Portal Video - Welcome to  Columbia Basin Hearing Center" },
      { id: "Txu-vputeyg", title: "Patient Portal Video - Why a Doctor of Audiology" },
      { id: "miAfxVZqISo", title: "Patient Portal Video - Common Symptoms of Hearing Loss" },
      { id: "R0lxS7I-rF4", title: "Patient Portal Video - Why are Hearing Aids SO Expensive" },
      { id: "4d1wFkB2foY", title: "Patient Portal Video - So You Have a Hearing Loss" },
      { id: "AgsLYNUASW0", title: "Dr. Shannon Explains what goes into our Practice!" },
    ],
  },
  {
    name: "DEVICE MAINTENANCE",
    videos: [
      { id: "AfWbFEE_rcE", title: "How to Clean My In-the-Ear Hearing Device" },
      { id: "p-UoBICp_9Y", title: "How to Clean a Receiver-in-the-Ear Hearing Device" },
      { id: "91OykdEouK0", title: "How to Clean a Behind-the-Ear Hearing Device" },
    ],
  },
  {
    name: "PATIENT STORIES",
    videos: [
      { id: "_N3OweXqgiw", title: "CBHC - Patient Stories - Lynn" },
      { id: "JVd0fiCQxUs", title: "CBHC Patient Stories - Ashley" },
      { id: "-vWWgQVnt0I", title: "CBHC Patient Story - Dempsey" },
      { id: "Zmxc1mir4qQ", title: "CBHC - Patient Stories - Brenna" },
      { id: "VdvCyAOlI2g", title: "CBHC - Patient Stories - Lorrie" },
    ],
  },
  {
    name: "CBHC HISTORY",
    videos: [
      { id: "Mm7DNbmp8ac", title: "An Interview with Dr. Frank, the Founder of Columbia Basin Hearing Center" },
      { id: "sozaqbg_GKQ", title: "Dr. Neil Aiello (former Owner of CBHC) gives an interview about Audiology and his Career." },
    ],
  },
  {
    name: "NEWS & SEGMENTS",
    videos: [
      { id: "ppGIrpEr4LE", title: "Hear 4U - 01 - Hearing Loss Symptoms" },
      { id: "7wn_Yik-71Y", title: "Hear 4U - 02 - I Have a Hearing Loss, Who Do I Call?" },
      { id: "XW-3dqq41OQ", title: "Hear 4U - 03 - How Can I Tell If My Earbuds Are Too Loud?" },
      { id: "KExw_uQ0_M4", title: "Hear 4U - 04 - What Does Hearing Loss Sound Like?" },
      { id: "izhRCbgtg90", title: "Hear 4U - 05  - What Are The Differences Between Hearing  Healthcare Professionals?" },
      { id: "UjChOcF85p0", title: "Hear 4U - 06  - Audiotory Processing Disorder" },
      { id: "nbsRwn4IHRQ", title: "Hear 4U - 07 - Hearing Protection For Yard Work" },
      { id: "AEBXZk-JQ3o", title: "Hear 4U - 08 - How NOT To Lose Your Hearing Devices" },
      { id: "B4nPYxsSfhw", title: "CBHC  - H4U - 09 - Musical Ear Syndrome" },
      { id: "v5VEfmFn2jY", title: "CBHC - H4U - 10 - Sudden Hearing Loss" },
      { id: "PJQd9NgyUgQ", title: "CBHC - H4U - 11 - How to Help Your Friends" },
      { id: "PdHiRru4w6E", title: "CBHC - H4U - 12 - Swimmers Ear" },
      { id: "-DNMGdE9CK0", title: "CBHC - H4U - 13 - Summertime Hearing Device Care" },
      { id: "kYlgTDZQgnU", title: "CBHC - H4U - 14 - Hearing Protection at Work" },
      { id: "heGUBKS6lf4", title: "CBHC - H4U - 15 - Back to School" },
      { id: "35LVFBi5oyg", title: "CBHC - H4U - 16 - Musicians and Hearing Loss" },
      { id: "0E1_l0ddMAU", title: "CBHC - H4U - 17 - Talking to Loved Ones" },
      { id: "wjO3-Kr4cPU", title: "CBHC - H4U - 18 - Ear Wax" },
      { id: "gTp_BEi4Xhc", title: "CBHC - H4U - 19   Hunters and Hearing Loss" },
      { id: "4aQwmb_7erQ", title: "CBHC - H4U - 20 - Hearing and the Brain" },
      { id: "9q9Wh5SK61s", title: "CBHC - H4U - 21 - Apple Devices" },
      { id: "kSvBuVamAkM", title: "CBHC - H4U - 22 - Hearing Care is Health Care" },
      { id: "xMtZ4osiB10", title: "CBHC - H4U - 23 - Hearing Aids for Free" },
      { id: "ZGKZF225pU8", title: "CBHC - H4U - 24 - Holiday Ready Hearing Aids" },
      { id: "_WpkYUg7ZOE", title: "CBHC - H4U - 25 - End of Year Hearing Treatment" },
      { id: "9Oq-DRUscOg", title: "CBHC - H4U - 26 - Hearing Loss and Chemotherapy" },
      { id: "rYHgQMiyn0M", title: "CBHC - H4U - 27 - Cochlear Implants" },
      { id: "5_Ej1zyGHeU", title: "CBHC - H4U - 28 -  3 Things Dr Shannon would NEVER do!" },
      { id: "r5rqJVbDe0c", title: "CBHC -  H4U -  29 -  Hearing Loss Symptoms" },
      { id: "Ng1j_DRVCJE", title: "CBHC - H4U -  30 -  Ear Infections" },
      { id: "bMgkME46nXg", title: "CBHC - H4U - 31 - Patient Experience Stories" },
      { id: "Sgedk7EMQik", title: "CBHC - H4U - 32 - Patient Experience Stories" },
      { id: "PptXA0n6HzI", title: "CBHC - H4U - 33 - Glasses for the Deaf?" },
      { id: "Vc2I47f5Vaw", title: "CBHC - H4U - 34 - Springtime Issues" },
      { id: "psNvTrIB0mo", title: "CBHC  - H4U  - 35  - On the Job Hearing Loss" },
      { id: "Q7lKUba84AY", title: "CBHC - H4U - 36 - Hearing Aids In Glasses" },
      { id: "0oguYHRG4Ts", title: "CBHC - H4U - 37 - Bone Conductors Vs  Earbuds" },
      { id: "4Ch_Z17hNmA", title: "CBHC -  H4U - 38 - Testing Children" },
      { id: "JRRr91TRgKY", title: "CBHC - H4U - 39 - Noisy Restaurants" },
      { id: "15t7GnI7MyI", title: "CBHC - H4U - 40 - Tinnitus Treatment" },
      { id: "uYmCWNTV7Xg", title: "CBHC - H4U - 41 - Yardwork and Protection 25" },
      { id: "XuV1xIXqiWM", title: "CBHC - H4U - 42 - How Long Do Hearing Aids Last" },
      { id: "R9wuY0AHYhA", title: "CBHC- H4U - 43 - Not One Size Fits All" },
      { id: "5a9j_kAon5U", title: "CBHC - H4U - 44 - Motorcycle Enthusiasts" },
      { id: "ZjrVonNlDv4", title: "CBHC - H4U - 45 - Swimmers Ear" },
      { id: "Ca-PRHFxZrM", title: "CBHC - H4U - 46 - Tinnitus" },
      { id: "XBmQD0RE5lQ", title: "CBHC - H4U - 47 - Hearing Aid Accessories" },
      { id: "0RnhI0lt0Bs", title: "CBHC - H4U - 48 - New Location" },
      { id: "Fljp0zBGV7U", title: "CBHC - H4U - 49 - Fireworks" },
      { id: "l3xZcl3lGZg", title: "CBHC - H4U - 50 - Hearing Your Spouse Better" },
      { id: "ZQQkBdIUDfQ", title: "CBHC - H4U - 51 - One Man's Story" },
      { id: "DSbN8yXkUK8", title: "CBHC - H4U - 52 - Back to School for Teachers" },
      { id: "pi-WAJk1koc", title: "CBHC - H4U - 53 - Back to School for Kids" },
      { id: "OBaHhhra1P8", title: "CBHC - H4U - 54 - Now Open in West Richland" },
      { id: "bxAE_JltdHQ", title: "CBHC - H4U - 55 - Hunting Season" },
      { id: "s-VYFylwZXg", title: "CBHC - H4U - 56 - Affordable Hearing Aids" },
      { id: "gxBxcY2hC8Y", title: "CBHC - H4U - 57 - West Richland Grand Opening" },
      { id: "OFDwQNdFGy8", title: "CBHC - H4U - 58 - The Talk" },
      { id: "viBP0LC6mPg", title: "CBHC - H4U - 59 - 3 Steps to be a Helpful Host for the Holidays" },
      { id: "Y63G1UF-hP8", title: "CBHC - H4U - 60 - Signs of Hearing Loss in a Loved One" },
      { id: "iEN2n1-cH_k", title: "CBHC- H4U- 61 -Student Hearing Loss" },
      { id: "JfV6_fjj0gs", title: "CBHC - H4U - 62 - Ear Pain" },
    ],
  },
  {
    name: "OTHER MEDIA",
    videos: [
      { id: "JbrwEZuYQTs", title: "We Help Heroes Everyday" },
      { id: "8ASwQlyVuz4", title: "What is an Audiological Processing Disorder?" },
      { id: "Xxi76aokZRs", title: "Columbia Basin Hearing Center at the Special Olympics Washington Spring 2024 Event" },
      { id: "sseeGcmjgKg", title: "Dr. Shannon Marie covers the Pro's and Con's of OTC Legislation" },
      { id: "tJolXG19bYc", title: "Engage Hearing Packages" },
      { id: "pmBbECzbUxw", title: "Experience at Columbia Basin Hearing" },
    ],
  },
];

export const VIDEO_LIBRARY: Video[] = VIDEO_SECTIONS.flatMap((s) => s.videos);
