/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoLibraryRouteImport } from './routes/video-library'
import { Route as TinnitusReliefManagementProgramRouteImport } from './routes/tinnitus-relief-management-program'
import { Route as ThirdPartyPayersRouteImport } from './routes/third-party-payers'
import { Route as TheLibraryRouteImport } from './routes/the-library'
import { Route as SoundShieldProgramRouteImport } from './routes/sound-shield-program'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PatientAmbassadorprogramRouteImport } from './routes/patient-ambassadorprogram'
import { Route as PatientAmbassadorProgramRouteImport } from './routes/patient-ambassador-program'
import { Route as OtcLegislationRouteImport } from './routes/otc-legislation'
import { Route as OnlineHearingScreeningRouteImport } from './routes/online-hearing-screening'
import { Route as NuanceCbhcRouteImport } from './routes/nuance-cbhc'
import { Route as LiExtendedProtectionRouteImport } from './routes/li-extended-protection'
import { Route as LenireFromNeuromodRouteImport } from './routes/lenire-from-neuromod'
import { Route as LaceAiProRouteImport } from './routes/lace-ai-pro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HearingUpRouteImport } from './routes/hearing-up'
import { Route as HearingHeroesRouteImport } from './routes/hearing-heroes'
import { Route as HearingRouteImport } from './routes/hearing'
import { Route as ForEducatorsRouteImport } from './routes/for-educators'
import { Route as EffectivelyCommunicatingWithAHearingLossRouteImport } from './routes/effectively-communicating-with-a-hearing-loss'
import { Route as DoYouHaveALossRouteImport } from './routes/do-you-have-a-loss'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AllPagesRouteImport } from './routes/all-pages'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlineStoreIndexRouteImport } from './routes/online-store/index'
import { Route as OnlineStoreCategoryRouteImport } from './routes/online-store/$category'
import { Route as OnlineStorePSlugRouteImport } from './routes/online-store/p.$slug'

const VideoLibraryRoute = VideoLibraryRouteImport.update({
  id: '/video-library',
  path: '/video-library',
  getParentRoute: () => rootRouteImport,
} as any)
const TinnitusReliefManagementProgramRoute =
  TinnitusReliefManagementProgramRouteImport.update({
    id: '/tinnitus-relief-management-program',
    path: '/tinnitus-relief-management-program',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThirdPartyPayersRoute = ThirdPartyPayersRouteImport.update({
  id: '/third-party-payers',
  path: '/third-party-payers',
  getParentRoute: () => rootRouteImport,
} as any)
const TheLibraryRoute = TheLibraryRouteImport.update({
  id: '/the-library',
  path: '/the-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundShieldProgramRoute = SoundShieldProgramRouteImport.update({
  id: '/sound-shield-program',
  path: '/sound-shield-program',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAmbassadorprogramRoute =
  PatientAmbassadorprogramRouteImport.update({
    id: '/patient-ambassadorprogram',
    path: '/patient-ambassadorprogram',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientAmbassadorProgramRoute =
  PatientAmbassadorProgramRouteImport.update({
    id: '/patient-ambassador-program',
    path: '/patient-ambassador-program',
    getParentRoute: () => rootRouteImport,
  } as any)
const OtcLegislationRoute = OtcLegislationRouteImport.update({
  id: '/otc-legislation',
  path: '/otc-legislation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineHearingScreeningRoute = OnlineHearingScreeningRouteImport.update({
  id: '/online-hearing-screening',
  path: '/online-hearing-screening',
  getParentRoute: () => rootRouteImport,
} as any)
const NuanceCbhcRoute = NuanceCbhcRouteImport.update({
  id: '/nuance-cbhc',
  path: '/nuance-cbhc',
  getParentRoute: () => rootRouteImport,
} as any)
const LiExtendedProtectionRoute = LiExtendedProtectionRouteImport.update({
  id: '/li-extended-protection',
  path: '/li-extended-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const LenireFromNeuromodRoute = LenireFromNeuromodRouteImport.update({
  id: '/lenire-from-neuromod',
  path: '/lenire-from-neuromod',
  getParentRoute: () => rootRouteImport,
} as any)
const LaceAiProRoute = LaceAiProRouteImport.update({
  id: '/lace-ai-pro',
  path: '/lace-ai-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingUpRoute = HearingUpRouteImport.update({
  id: '/hearing-up',
  path: '/hearing-up',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingHeroesRoute = HearingHeroesRouteImport.update({
  id: '/hearing-heroes',
  path: '/hearing-heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingRoute = HearingRouteImport.update({
  id: '/hearing',
  path: '/hearing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEducatorsRoute = ForEducatorsRouteImport.update({
  id: '/for-educators',
  path: '/for-educators',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectivelyCommunicatingWithAHearingLossRoute =
  EffectivelyCommunicatingWithAHearingLossRouteImport.update({
    id: '/effectively-communicating-with-a-hearing-loss',
    path: '/effectively-communicating-with-a-hearing-loss',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoYouHaveALossRoute = DoYouHaveALossRouteImport.update({
  id: '/do-you-have-a-loss',
  path: '/do-you-have-a-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPagesRoute = AllPagesRouteImport.update({
  id: '/all-pages',
  path: '/all-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineStoreIndexRoute = OnlineStoreIndexRouteImport.update({
  id: '/online-store/',
  path: '/online-store/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineStoreCategoryRoute = OnlineStoreCategoryRouteImport.update({
  id: '/online-store/$category',
  path: '/online-store/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineStorePSlugRoute = OnlineStorePSlugRouteImport.update({
  id: '/online-store/p/$slug',
  path: '/online-store/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/all-pages': typeof AllPagesRoute
  '/contact-us': typeof ContactUsRoute
  '/do-you-have-a-loss': typeof DoYouHaveALossRoute
  '/effectively-communicating-with-a-hearing-loss': typeof EffectivelyCommunicatingWithAHearingLossRoute
  '/for-educators': typeof ForEducatorsRoute
  '/hearing': typeof HearingRoute
  '/hearing-heroes': typeof HearingHeroesRoute
  '/hearing-up': typeof HearingUpRoute
  '/home': typeof HomeRoute
  '/lace-ai-pro': typeof LaceAiProRoute
  '/lenire-from-neuromod': typeof LenireFromNeuromodRoute
  '/li-extended-protection': typeof LiExtendedProtectionRoute
  '/nuance-cbhc': typeof NuanceCbhcRoute
  '/online-hearing-screening': typeof OnlineHearingScreeningRoute
  '/otc-legislation': typeof OtcLegislationRoute
  '/patient-ambassador-program': typeof PatientAmbassadorProgramRoute
  '/patient-ambassadorprogram': typeof PatientAmbassadorprogramRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sound-shield-program': typeof SoundShieldProgramRoute
  '/the-library': typeof TheLibraryRoute
  '/third-party-payers': typeof ThirdPartyPayersRoute
  '/tinnitus-relief-management-program': typeof TinnitusReliefManagementProgramRoute
  '/video-library': typeof VideoLibraryRoute
  '/online-store/$category': typeof OnlineStoreCategoryRoute
  '/online-store/': typeof OnlineStoreIndexRoute
  '/online-store/p/$slug': typeof OnlineStorePSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/all-pages': typeof AllPagesRoute
  '/contact-us': typeof ContactUsRoute
  '/do-you-have-a-loss': typeof DoYouHaveALossRoute
  '/effectively-communicating-with-a-hearing-loss': typeof EffectivelyCommunicatingWithAHearingLossRoute
  '/for-educators': typeof ForEducatorsRoute
  '/hearing': typeof HearingRoute
  '/hearing-heroes': typeof HearingHeroesRoute
  '/hearing-up': typeof HearingUpRoute
  '/home': typeof HomeRoute
  '/lace-ai-pro': typeof LaceAiProRoute
  '/lenire-from-neuromod': typeof LenireFromNeuromodRoute
  '/li-extended-protection': typeof LiExtendedProtectionRoute
  '/nuance-cbhc': typeof NuanceCbhcRoute
  '/online-hearing-screening': typeof OnlineHearingScreeningRoute
  '/otc-legislation': typeof OtcLegislationRoute
  '/patient-ambassador-program': typeof PatientAmbassadorProgramRoute
  '/patient-ambassadorprogram': typeof PatientAmbassadorprogramRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sound-shield-program': typeof SoundShieldProgramRoute
  '/the-library': typeof TheLibraryRoute
  '/third-party-payers': typeof ThirdPartyPayersRoute
  '/tinnitus-relief-management-program': typeof TinnitusReliefManagementProgramRoute
  '/video-library': typeof VideoLibraryRoute
  '/online-store/$category': typeof OnlineStoreCategoryRoute
  '/online-store': typeof OnlineStoreIndexRoute
  '/online-store/p/$slug': typeof OnlineStorePSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/all-pages': typeof AllPagesRoute
  '/contact-us': typeof ContactUsRoute
  '/do-you-have-a-loss': typeof DoYouHaveALossRoute
  '/effectively-communicating-with-a-hearing-loss': typeof EffectivelyCommunicatingWithAHearingLossRoute
  '/for-educators': typeof ForEducatorsRoute
  '/hearing': typeof HearingRoute
  '/hearing-heroes': typeof HearingHeroesRoute
  '/hearing-up': typeof HearingUpRoute
  '/home': typeof HomeRoute
  '/lace-ai-pro': typeof LaceAiProRoute
  '/lenire-from-neuromod': typeof LenireFromNeuromodRoute
  '/li-extended-protection': typeof LiExtendedProtectionRoute
  '/nuance-cbhc': typeof NuanceCbhcRoute
  '/online-hearing-screening': typeof OnlineHearingScreeningRoute
  '/otc-legislation': typeof OtcLegislationRoute
  '/patient-ambassador-program': typeof PatientAmbassadorProgramRoute
  '/patient-ambassadorprogram': typeof PatientAmbassadorprogramRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sound-shield-program': typeof SoundShieldProgramRoute
  '/the-library': typeof TheLibraryRoute
  '/third-party-payers': typeof ThirdPartyPayersRoute
  '/tinnitus-relief-management-program': typeof TinnitusReliefManagementProgramRoute
  '/video-library': typeof VideoLibraryRoute
  '/online-store/$category': typeof OnlineStoreCategoryRoute
  '/online-store/': typeof OnlineStoreIndexRoute
  '/online-store/p/$slug': typeof OnlineStorePSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/all-pages'
    | '/contact-us'
    | '/do-you-have-a-loss'
    | '/effectively-communicating-with-a-hearing-loss'
    | '/for-educators'
    | '/hearing'
    | '/hearing-heroes'
    | '/hearing-up'
    | '/home'
    | '/lace-ai-pro'
    | '/lenire-from-neuromod'
    | '/li-extended-protection'
    | '/nuance-cbhc'
    | '/online-hearing-screening'
    | '/otc-legislation'
    | '/patient-ambassador-program'
    | '/patient-ambassadorprogram'
    | '/services'
    | '/sitemap.xml'
    | '/sound-shield-program'
    | '/the-library'
    | '/third-party-payers'
    | '/tinnitus-relief-management-program'
    | '/video-library'
    | '/online-store/$category'
    | '/online-store/'
    | '/online-store/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/all-pages'
    | '/contact-us'
    | '/do-you-have-a-loss'
    | '/effectively-communicating-with-a-hearing-loss'
    | '/for-educators'
    | '/hearing'
    | '/hearing-heroes'
    | '/hearing-up'
    | '/home'
    | '/lace-ai-pro'
    | '/lenire-from-neuromod'
    | '/li-extended-protection'
    | '/nuance-cbhc'
    | '/online-hearing-screening'
    | '/otc-legislation'
    | '/patient-ambassador-program'
    | '/patient-ambassadorprogram'
    | '/services'
    | '/sitemap.xml'
    | '/sound-shield-program'
    | '/the-library'
    | '/third-party-payers'
    | '/tinnitus-relief-management-program'
    | '/video-library'
    | '/online-store/$category'
    | '/online-store'
    | '/online-store/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/all-pages'
    | '/contact-us'
    | '/do-you-have-a-loss'
    | '/effectively-communicating-with-a-hearing-loss'
    | '/for-educators'
    | '/hearing'
    | '/hearing-heroes'
    | '/hearing-up'
    | '/home'
    | '/lace-ai-pro'
    | '/lenire-from-neuromod'
    | '/li-extended-protection'
    | '/nuance-cbhc'
    | '/online-hearing-screening'
    | '/otc-legislation'
    | '/patient-ambassador-program'
    | '/patient-ambassadorprogram'
    | '/services'
    | '/sitemap.xml'
    | '/sound-shield-program'
    | '/the-library'
    | '/third-party-payers'
    | '/tinnitus-relief-management-program'
    | '/video-library'
    | '/online-store/$category'
    | '/online-store/'
    | '/online-store/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AllPagesRoute: typeof AllPagesRoute
  ContactUsRoute: typeof ContactUsRoute
  DoYouHaveALossRoute: typeof DoYouHaveALossRoute
  EffectivelyCommunicatingWithAHearingLossRoute: typeof EffectivelyCommunicatingWithAHearingLossRoute
  ForEducatorsRoute: typeof ForEducatorsRoute
  HearingRoute: typeof HearingRoute
  HearingHeroesRoute: typeof HearingHeroesRoute
  HearingUpRoute: typeof HearingUpRoute
  HomeRoute: typeof HomeRoute
  LaceAiProRoute: typeof LaceAiProRoute
  LenireFromNeuromodRoute: typeof LenireFromNeuromodRoute
  LiExtendedProtectionRoute: typeof LiExtendedProtectionRoute
  NuanceCbhcRoute: typeof NuanceCbhcRoute
  OnlineHearingScreeningRoute: typeof OnlineHearingScreeningRoute
  OtcLegislationRoute: typeof OtcLegislationRoute
  PatientAmbassadorProgramRoute: typeof PatientAmbassadorProgramRoute
  PatientAmbassadorprogramRoute: typeof PatientAmbassadorprogramRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoundShieldProgramRoute: typeof SoundShieldProgramRoute
  TheLibraryRoute: typeof TheLibraryRoute
  ThirdPartyPayersRoute: typeof ThirdPartyPayersRoute
  TinnitusReliefManagementProgramRoute: typeof TinnitusReliefManagementProgramRoute
  VideoLibraryRoute: typeof VideoLibraryRoute
  OnlineStoreCategoryRoute: typeof OnlineStoreCategoryRoute
  OnlineStoreIndexRoute: typeof OnlineStoreIndexRoute
  OnlineStorePSlugRoute: typeof OnlineStorePSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-library': {
      id: '/video-library'
      path: '/video-library'
      fullPath: '/video-library'
      preLoaderRoute: typeof VideoLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tinnitus-relief-management-program': {
      id: '/tinnitus-relief-management-program'
      path: '/tinnitus-relief-management-program'
      fullPath: '/tinnitus-relief-management-program'
      preLoaderRoute: typeof TinnitusReliefManagementProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third-party-payers': {
      id: '/third-party-payers'
      path: '/third-party-payers'
      fullPath: '/third-party-payers'
      preLoaderRoute: typeof ThirdPartyPayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-library': {
      id: '/the-library'
      path: '/the-library'
      fullPath: '/the-library'
      preLoaderRoute: typeof TheLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-shield-program': {
      id: '/sound-shield-program'
      path: '/sound-shield-program'
      fullPath: '/sound-shield-program'
      preLoaderRoute: typeof SoundShieldProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-ambassadorprogram': {
      id: '/patient-ambassadorprogram'
      path: '/patient-ambassadorprogram'
      fullPath: '/patient-ambassadorprogram'
      preLoaderRoute: typeof PatientAmbassadorprogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-ambassador-program': {
      id: '/patient-ambassador-program'
      path: '/patient-ambassador-program'
      fullPath: '/patient-ambassador-program'
      preLoaderRoute: typeof PatientAmbassadorProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otc-legislation': {
      id: '/otc-legislation'
      path: '/otc-legislation'
      fullPath: '/otc-legislation'
      preLoaderRoute: typeof OtcLegislationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-hearing-screening': {
      id: '/online-hearing-screening'
      path: '/online-hearing-screening'
      fullPath: '/online-hearing-screening'
      preLoaderRoute: typeof OnlineHearingScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuance-cbhc': {
      id: '/nuance-cbhc'
      path: '/nuance-cbhc'
      fullPath: '/nuance-cbhc'
      preLoaderRoute: typeof NuanceCbhcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/li-extended-protection': {
      id: '/li-extended-protection'
      path: '/li-extended-protection'
      fullPath: '/li-extended-protection'
      preLoaderRoute: typeof LiExtendedProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenire-from-neuromod': {
      id: '/lenire-from-neuromod'
      path: '/lenire-from-neuromod'
      fullPath: '/lenire-from-neuromod'
      preLoaderRoute: typeof LenireFromNeuromodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lace-ai-pro': {
      id: '/lace-ai-pro'
      path: '/lace-ai-pro'
      fullPath: '/lace-ai-pro'
      preLoaderRoute: typeof LaceAiProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-up': {
      id: '/hearing-up'
      path: '/hearing-up'
      fullPath: '/hearing-up'
      preLoaderRoute: typeof HearingUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-heroes': {
      id: '/hearing-heroes'
      path: '/hearing-heroes'
      fullPath: '/hearing-heroes'
      preLoaderRoute: typeof HearingHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing': {
      id: '/hearing'
      path: '/hearing'
      fullPath: '/hearing'
      preLoaderRoute: typeof HearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-educators': {
      id: '/for-educators'
      path: '/for-educators'
      fullPath: '/for-educators'
      preLoaderRoute: typeof ForEducatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effectively-communicating-with-a-hearing-loss': {
      id: '/effectively-communicating-with-a-hearing-loss'
      path: '/effectively-communicating-with-a-hearing-loss'
      fullPath: '/effectively-communicating-with-a-hearing-loss'
      preLoaderRoute: typeof EffectivelyCommunicatingWithAHearingLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-you-have-a-loss': {
      id: '/do-you-have-a-loss'
      path: '/do-you-have-a-loss'
      fullPath: '/do-you-have-a-loss'
      preLoaderRoute: typeof DoYouHaveALossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-pages': {
      id: '/all-pages'
      path: '/all-pages'
      fullPath: '/all-pages'
      preLoaderRoute: typeof AllPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-store/': {
      id: '/online-store/'
      path: '/online-store'
      fullPath: '/online-store/'
      preLoaderRoute: typeof OnlineStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-store/$category': {
      id: '/online-store/$category'
      path: '/online-store/$category'
      fullPath: '/online-store/$category'
      preLoaderRoute: typeof OnlineStoreCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-store/p/$slug': {
      id: '/online-store/p/$slug'
      path: '/online-store/p/$slug'
      fullPath: '/online-store/p/$slug'
      preLoaderRoute: typeof OnlineStorePSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AllPagesRoute: AllPagesRoute,
  ContactUsRoute: ContactUsRoute,
  DoYouHaveALossRoute: DoYouHaveALossRoute,
  EffectivelyCommunicatingWithAHearingLossRoute:
    EffectivelyCommunicatingWithAHearingLossRoute,
  ForEducatorsRoute: ForEducatorsRoute,
  HearingRoute: HearingRoute,
  HearingHeroesRoute: HearingHeroesRoute,
  HearingUpRoute: HearingUpRoute,
  HomeRoute: HomeRoute,
  LaceAiProRoute: LaceAiProRoute,
  LenireFromNeuromodRoute: LenireFromNeuromodRoute,
  LiExtendedProtectionRoute: LiExtendedProtectionRoute,
  NuanceCbhcRoute: NuanceCbhcRoute,
  OnlineHearingScreeningRoute: OnlineHearingScreeningRoute,
  OtcLegislationRoute: OtcLegislationRoute,
  PatientAmbassadorProgramRoute: PatientAmbassadorProgramRoute,
  PatientAmbassadorprogramRoute: PatientAmbassadorprogramRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoundShieldProgramRoute: SoundShieldProgramRoute,
  TheLibraryRoute: TheLibraryRoute,
  ThirdPartyPayersRoute: ThirdPartyPayersRoute,
  TinnitusReliefManagementProgramRoute: TinnitusReliefManagementProgramRoute,
  VideoLibraryRoute: VideoLibraryRoute,
  OnlineStoreCategoryRoute: OnlineStoreCategoryRoute,
  OnlineStoreIndexRoute: OnlineStoreIndexRoute,
  OnlineStorePSlugRoute: OnlineStorePSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
